In [1]:
import numpy as np

数组

In [2]:
a = np.array([1,2,3,4])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array((1,2,3,4))

In [5]:
a = np.array([[1,2,3], [4,5,6]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b = [[1,2,3], [4,5,6]]

In [8]:
b + 1

TypeError: can only concatenate list (not "int") to list

In [9]:
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
b + b

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [11]:
a + a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
b * 2

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [13]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [15]:
b * b

TypeError: can't multiply sequence by non-int of type 'list'

In [16]:
a * a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

数组的属性：

In [18]:
a.shape

(2, 3)

In [19]:
c = np.array([1,2,3])

In [20]:
c.shape

(3,)

In [21]:
np.shape(a)

(2, 3)

In [22]:
b

[[1, 2, 3], [4, 5, 6]]

In [23]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [24]:
np.shape(b)

(2, 3)

In [25]:
np.shape(1231)

()

标量，形状是一个空元组

In [26]:
a.dtype

dtype('int64')

data type 数据类型

In [27]:
[1, 2, "sad", [1,2,3,4]]

[1, 2, 'sad', [1, 2, 3, 4]]

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.itemsize

8

In [30]:
a.size

6

In [31]:
np.size(a)

6

In [32]:
np.size(b)

6

In [33]:
a.nbytes

48

In [34]:
a.ndim

2

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a.fill(7.3)

In [37]:
a

array([[7, 7, 7],
       [7, 7, 7]])

In [38]:
a.dtype

dtype('int64')

类型：

In [39]:
a = np.array([1,2,3,4])

In [40]:
a.dtype

dtype('int64')

In [41]:
a = np.array([1,2,3,4.0])
a

array([ 1.,  2.,  3.,  4.])

In [42]:
a.dtype

dtype('float64')

In [43]:
a = np.array([1,2,3+2j,4.0])
a.dtype

dtype('complex128')

虚部（Image）

In [44]:
a.imag

array([ 0.,  0.,  2.,  0.])

实部（Real）

In [45]:
a.real

array([ 1.,  2.,  3.,  4.])

In [46]:
a.conj()

array([ 1.-0.j,  2.-0.j,  3.-2.j,  4.-0.j])

In [47]:
a = np.array([1,2,"123"])

In [48]:
a.dtype

dtype('<U21')

In [53]:
a = np.array([1,2.2,"123"], dtype=int)

In [54]:
a

array([  1,   2, 123])

In [52]:
a.dtype

dtype('int64')

```python
bool, int, float, complex, str
np.float32, np.float64, np.int32, np.int64
"float", "int", "float32"
```

In [56]:
a = np.array([1,2.2,"123", [1, 2]], dtype=object)

In [59]:
a.shape

(4,)

In [60]:
a * 2

array([2, 4.4, '123123', list([1, 2, 1, 2])], dtype=object)

In [61]:
a = np.array([1, 2, 3])

In [62]:
a

array([1, 2, 3])

In [63]:
np.array(a, dtype="float")

array([ 1.,  2.,  3.])

In [64]:
np.asarray(a, dtype="float")

array([ 1.,  2.,  3.])

In [66]:
np.array(a, dtype=int) is a

False

In [67]:
np.asarray(a, dtype=int) is a

True

In [68]:
a.astype(float)

array([ 1.,  2.,  3.])

In [69]:
a

array([1, 2, 3])

无穷大：

In [70]:
np.inf

inf

不合法的数，not a number(nan)

In [71]:
np.nan

nan

In [74]:
a = np.array([1., -1, 0])

In [78]:
a / 0

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf, -inf,  nan])

数组的生成：

In [83]:
a = np.zeros((2, 3))

In [84]:
a.shape

(2, 3)

In [85]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [86]:
a = np.ones((2, 3))

In [87]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [91]:
np.arange(10.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [92]:
np.arange(1, 10.0, 2.5)

array([ 1. ,  3.5,  6. ,  8.5])

In [93]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [95]:
a = np.linspace(0, 10)
a.shape

(50,)

索引：

In [96]:
a = np.arange(5)

In [97]:
a

array([0, 1, 2, 3, 4])

In [98]:
a[0]

0

In [99]:
a[-1]

4

In [100]:
a[1:]

array([1, 2, 3, 4])

In [101]:
a[1::2]

array([1, 3])

In [102]:
a = np.arange(20)

In [103]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [104]:
a.shape

(20,)

In [105]:
a.shape = 4, 5

In [106]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [107]:
a.ndim

2

In [108]:
a[0][0]

0

In [110]:
a[0][0]

0

推荐的方法：

In [111]:
a[0, 0]

0

In [112]:
a[-1, -1]

19

In [113]:
a[0, -1]

4

In [114]:
a[:, 1]

array([ 1,  6, 11, 16])

In [115]:
a[1:3, 1]

array([ 6, 11])

In [116]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

迭代：

In [117]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [120]:
for i in a:
    print(i)
    print(type(i))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[5 6 7 8 9]
<class 'numpy.ndarray'>
[10 11 12 13 14]
<class 'numpy.ndarray'>
[15 16 17 18 19]
<class 'numpy.ndarray'>


In [119]:
print([1,2,3,4])

[1, 2, 3, 4]


In [121]:
for idx, v in np.ndenumerate(a):
    print(idx, v)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14
(3, 0) 15
(3, 1) 16
(3, 2) 17
(3, 3) 18
(3, 4) 19


操作：

In [122]:
a.sum()

190

In [123]:
a.sum(axis=0)

array([30, 34, 38, 42, 46])

In [125]:
a.sum(axis=1)

array([10, 35, 60, 85])

In [126]:
a.shape

(4, 5)

In [127]:
b = np.arange(100)

In [128]:
b.shape = 2, 5, 10

In [132]:
b.shape

(2, 5, 10)

In [131]:
b.sum(axis=0).shape

(5, 10)

In [133]:
b.sum(axis=1).shape

(2, 10)

In [136]:
a.prod(axis=1)

array([      0,   15120,  240240, 1395360])

In [137]:
a.max(axis=1)

array([ 4,  9, 14, 19])

In [138]:
a.min(axis=1)

array([ 0,  5, 10, 15])

In [139]:
a.argmax(axis=1)

array([4, 4, 4, 4])

In [142]:
a.argmin(axis=1)

array([0, 0, 0, 0])

In [143]:
a.argmin()

0

In [144]:
a.argmax()

19

In [146]:
a = a * 2

In [147]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [148]:
a.argmax()

19

In [150]:
a.mean(axis=1)

array([  4.,  14.,  24.,  34.])

特殊的索引：

In [152]:
a.shape

(4, 5)

In [154]:
a[:, None, :].shape

(4, 1, 5)

In [156]:
a[None, :, :].shape

(1, 4, 5)

In [157]:
a.shape

(4, 5)

In [158]:
a.T

array([[ 0, 10, 20, 30],
       [ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38]])

In [159]:
a.T.shape

(5, 4)

拼接：

In [160]:
a = np.arange(6)
b = np.arange(10, 16)
a.shape = 2, 3
b.shape = 2, 3

In [161]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [162]:
b

array([[10, 11, 12],
       [13, 14, 15]])

In [163]:
a.shape

(2, 3)

In [164]:
b.shape

(2, 3)

In [166]:
np.concatenate([a, b]).shape

(4, 3)

In [167]:
np.concatenate([a, b], axis=0).shape

(4, 3)

In [168]:
np.concatenate([a, b], axis=1).shape

(2, 6)

In [169]:
c = np.arange(3)

In [170]:
c.shape = 1, 3

In [171]:
c

array([[0, 1, 2]])

In [174]:
np.concatenate([a, c], axis=1).shape

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [173]:
a.shape

(2, 3)

In [176]:
c.shape

(1, 3)

In [177]:
np.vstack((a,b)).shape # vertical

(4, 3)

In [178]:
np.hstack((a,b)).shape # 

(2, 6)

In [179]:
np.dstack((a,b)).shape

(2, 3, 2)

运算：

In [180]:
a = np.array([[1, 2],
              [3, 4]])

In [181]:
a

array([[1, 2],
       [3, 4]])

In [182]:
a + 1

array([[2, 3],
       [4, 5]])

In [183]:
a + a

array([[2, 4],
       [6, 8]])

In [184]:
a / a

array([[ 1.,  1.],
       [ 1.,  1.]])

In [185]:
a / 2

array([[ 0.5,  1. ],
       [ 1.5,  2. ]])

In [186]:
a - a

array([[0, 0],
       [0, 0]])

In [187]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [188]:
a ** a

array([[  1,   4],
       [ 27, 256]])

In [189]:
a % 2

array([[1, 0],
       [1, 0]])

矩阵：

In [190]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [191]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [192]:
a @ a

array([[ 7, 10],
       [15, 22]])

In [193]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [194]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [195]:
a > 3

array([[False, False],
       [False,  True]], dtype=bool)

In [197]:
if np.all(a > 0):
    print("hi")

hi


In [198]:
if np.any(a > 3):
    print("hi")

hi


In [199]:
a = np.array([1.1,2.1])

In [205]:
a == np.array([1.3,2.3])-0.2

array([False, False], dtype=bool)

In [209]:
np.allclose?

数组广播机制：

In [210]:
a = np.array([[0,1],[0,1], [0,1]])
b = np.array([[1,1], [2,2], [3,3]])

In [211]:
a

array([[0, 1],
       [0, 1],
       [0, 1]])

In [212]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [213]:
a +  b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [214]:
a.shape

(3, 2)

In [215]:
a = np.array([0,1])

In [216]:
a.shape

(2,)

In [217]:
b.shape

(3, 2)

In [218]:
a + b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [219]:
b = np.array([[1],[2],[3]])

In [220]:
b.shape

(3, 1)

In [221]:
a + b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [222]:
a.shape

(2,)

两个数组维度不一样，低维的前面补1

- 3,1
- 1,2

维度一样，看每个维度的形状
- 形状一样
- 其中一个为1

数组广播的机制（Broadcasting）

- a: 256, 256, 3
- b: 1, 1, 3
- a+b: 256, 256, 3

- a: 7, 5, 4, 3
- b: 1, 5, 1, 1
- a+b:7,5,4,3

花式索引，fancy indexing

In [229]:
a = [1,2,3,4,5]

In [230]:
a[[1,3,4]]

TypeError: list indices must be integers or slices, not list

In [231]:
a = np.array([1,2,3,4,5])
a[[1,3,4]]

array([2, 4, 5])

随机数组：

In [233]:
np.random.rand(2,3) # 均匀分布

array([[ 0.47817252,  0.84833482,  0.76502285],
       [ 0.42553625,  0.69059945,  0.51428757]])

In [234]:
np.random.randn(2,3) # 高斯分布

array([[ 0.06310485, -0.87695978,  1.39967991],
       [-1.63730332, -1.42277347,  0.30689864]])