In [1]:
import numpy as np

In [2]:
import scipy.stats

In [6]:
a = np.array([1.56, 1.87, 1.90, 2.1, 1.3, 1.3])

In [7]:
a.max()

2.1000000000000001

In [8]:
a.min()

1.3

In [10]:
r =scipy.stats.mode(a) # 众数 mode

In [11]:
r

ModeResult(mode=array([ 1.3]), count=array([2]))

In [12]:
r.mode

array([ 1.3])

In [13]:
r.count

array([2])

In [15]:
scipy.stats.skew(a) # 偏度

-0.03346256215475293

In [16]:
scipy.stats.kurtosis(a) # 峰度

-1.560229204649697

In [17]:
from scipy.stats import norm

In [18]:
x_norm = norm.rvs(size=(2, 3))

In [19]:
x_norm

array([[-0.92070765, -0.64738959, -1.36077675],
       [-0.85447651,  0.88125683, -0.79552372]])

In [20]:
from scipy.stats import expon

In [21]:
expon.rvs(size=(2,3))

array([[ 0.96518092,  0.62051483,  0.61968932],
       [ 0.02559037,  0.9350882 ,  0.43053109]])

假设检验

积分：

In [22]:
from scipy.integrate import quad

In [23]:
x = np.linspace(0, np.pi)

In [24]:
quad(np.sin, 0, np.pi)

(2.0, 2.220446049250313e-14)

In [25]:
from scipy import linalg

In [26]:
a = np.array([[1,2], [3,4]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [29]:
a @ linalg.inv(a) # 逆矩阵

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])

In [30]:
linalg.det(a) # 行列式

-2.0

In [32]:
linalg.norm(a) # 模，范数

5.4772255750516612

In [33]:
linalg.norm(a, 1)

6.0

In [34]:
linalg.norm(a, -np.inf)

3.0

In [36]:
l, v = linalg.eig(a) # 特征值分解

In [37]:
l

array([-0.37228132+0.j,  5.37228132+0.j])

In [38]:
v

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [39]:
U, s, Vh = linalg.svd(a) # 奇异值分解

In [40]:
U

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [41]:
s

array([ 5.4649857 ,  0.36596619])

In [42]:
Vh

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])